# Ensemble Methodes/ Techniques

* It is used for larg amount of data set 

* Entire dataset devided into chunks of data set and these chunks run by a seperate model 

* Seperate accuracy of every model combined together and create "Mean Accuracy"

It hase 2 Types 

1) Bagging (parallel Method) -: * RandomForestclassifer(Mostly use)/ 
                                * Extra trees (use for huge dataset)
        
2) Boosting (Serial Method) -: *AdaBoostclassifer/ 
                               *GradientBoostclassifer,/ *votingclassifier

In [1]:
import pandas as pd
import numpy as np 
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
ds=load_iris()
ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
df=pd.DataFrame(data=ds.data)

In [4]:
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [5]:
df=pd.DataFrame(data=ds.data,columns=ds.feature_names)

In [6]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
df['target']=pd.DataFrame(ds.target)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [8]:
x=df.iloc[:,0:-1]
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y=df.iloc[:,-1]

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

# Bagging 

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf=RandomForestClassifier(n_estimators=100,random_state=42)
#here estimator 100 is default but we can apply estimator 50,100,150,200,250
# the estimator is depend on the hugeness of data. it should no more than 250 
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)
print(accuracy_score(y_test,rf_pred))
print(classification_report(y_test,rf_pred))
print(confusion_matrix(y_test,rf_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# Boost

In [14]:
from sklearn.ensemble import AdaBoostClassifier

In [15]:
# N_estimator is default 50 here and we can give it as per the data set like 100,150,200,250
ada=AdaBoostClassifier(n_estimators=50,base_estimator=DecisionTreeClassifier(),learning_rate=1.0)
#  the bracket section is default here
ada.fit(x_train,y_train)
ada_pred=ada.predict(x_test)
print(accuracy_score(y_test,ada_pred))
print(classification_report(y_test,ada_pred))
print(confusion_matrix(y_test,ada_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


 AdaBoost  in SVC classifier

there are 2 main algorithm in AdaBoost Classifier 

1) Default algorithm is "SAMME.R" -: This algorithm work when SVC has default Kernel ('rbf')
    
2) Algorithm "SAMME" -: This algorithm we have to use when SVC has another kernel like ("Linear","poly")

In [22]:
#when it is default then 
from sklearn.svm import SVC
sv=SVC()
ad=AdaBoostClassifier(n_estimators=100,base_estimator=SVC,algorithm='SAMME.R')
#here default SVC(kernel='rbf') that is why default Adaboost Algorithm is ('SAMME.R')
ad.fit(x_train,y_train)

TypeError: Cannot clone object. You should provide an instance of scikit-learn estimator instead of a class.

In [ ]:

ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(classification_report(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))

In [20]:
# if the SVC has kernel 
sv=SVC(kernel='Linear')
ad=AdaBoostClassifier(n_estimators=50,base_estimator=SVC,algorithm='SAMME')

In [21]:
ad.fit(x_train,y_train)

TypeError: Cannot clone object. You should provide an instance of scikit-learn estimator instead of a class.